import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/lib/CartContext";
import { ShoppingCart } from "lucide-react";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <nav className="bg-white p-4 shadow-sm sticky top-0 z-50">
            <div className="max-w-7xl mx-auto flex justify-between items-center">
              <div className="text-xl md:text-2xl font-bold text-primary flex items-center">
                <img
                  src={
                    "https://reqrsmboabgxshacmkst.supabase.co/storage/v1/object/sign/product-images/logo.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZGU3NTY3OC0zMDRhLTQ3OTUtYjdhZC04M2IwMzM3ZDY2ZTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwcm9kdWN0LWltYWdlcy9sb2dvLmpwZyIsImlhdCI6MTc1NTc3OTI0OCwiZXhwIjoxNzg3MzE1MjQ4fQ.mH40B7DKfxFPncSm9ZjXk_Uj0z9L8HUSgL3crorYywE"
                  }
                  alt={"Logo Hug Nature"}
                  className={"w-20 h-20 object-contain"}
                />
              </div>
              <div className="hidden md:flex space-x-6">
                <a
                  href="#"
                  className="text-gray-600 hover:text-[#d1bba3] transition-colors duration-300 font-medium"
                >
                  Home
                </a>
                <a
                  href="#"
                  className="text-gray-600 hover:text-hover transition-colors duration-300 font-medium"
                >
                  Shop
                </a>
                <a
                  href="#"
                  className="text-gray-600 hover:text-indigo-600 transition-colors duration-300 font-medium"
                >
                  About
                </a>
                <a
                  href="#"
                  className="text-gray-600 hover:text-indigo-600 transition-colors duration-300 font-medium"
                >
                  Contact
                </a>
              </div>
              <button className="bg-primary text-white px-4 py-2 rounded-lg shadow-md hover:bg-primary transition-colors duration-300 flex items-center text-sm md:text-base">
                <ShoppingCart className="w-4 h-4 md:w-5 md:h-5 mr-2" />
                Cart
              </button>
            </div>
          </nav>
          <main>{children}</main>
        </CartProvider>
      </body>
    </html>
  );
}
