export interface ShipmentHistoryItem {
    AWB: string;
    FromAddress: string;
    FromPhone: string;
    FromContactPerson: string;
    ToConsigneeName: string;
    ToAddress: string;
    ToPhone: string;
    ToMobile: string;
    ToRef: string;
    ToContactPerson: string;
    COD: number;
    Weight: number;
    Pieces: string;
    Contents: string;
    SpecialInstuctions: string;
    Data1: string;
    Data2: string;
    Data3: string;
    Data4: string;
    FromCityName: string;
    ToCityName: string;
    ClientName: string;
    SubAccountName: string;
    ProductName: string;
    ClientAccNo: string;
    StatusNameE: string;
    ReasonNameE: string;
    AWBvsAWB: string;
    Collected: string;
    PaidToCust: string;
    UpdateNotes: string;
    DeliveryDate: string;
    DeliveryTime: string;
    PickupDate: string;
    ArriveDate: string;
    AuditDate: string;
    ShipperNotes: string;
    Attempt1: string | null;
    Attempt2: string | null;
    Attempt3: string | null;
    Attempt4: string | null;
    Attempt5: string | null;
    TotalAttempts: number;
    VisitLat: number;
    VisitLon: number;
    CurrentBranch: string;
    FromBranch: string;
    ToBranch: string;
    VehicleType: string;
    RunnerName: string;
    RunnerCode: string;
}
